name: Feature Request
description: Suggest an improvement or request app support
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Got an idea? Let's hear it.

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: |
        A new animation style, app support, UI tweak, anything goes.

        For app support requests, include the package name if you know it:
        adb shell pm list packages | grep <name>
    validations:
      required: true
